package com.coactivity.controller.dto.response;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Response payload returned after successful user registration.
 * <p>
 * Provides the essential information needed by the client to proceed with the application flow
 * after a new user account is created.
 * </p>
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class RegistrationResponse {

  /**
   * Unique identifier assigned to the newly registered user.
   * <p>
   * This ID is generated by the server and must be used by the client for all future user-specific
   * API calls. The client should store this value securely for the duration of the user's session.
   * </p>
   */
  private Integer userId;

  /**
   * Public display name chosen during registration.
   * <p>
   * Provided as confirmation that the registration processed correctly. This value can be displayed
   * in the UI to welcome the new user.
   * </p>
   */
  private String userName;
}