spring.application.name=qa-service
server.port=${QA_SERVICE_PORT:8081}
management.endpoints.web.exposure.include=health,info

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5430/postgres_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}

security.jwt.secret-base64=${JWT_SECRET_BASE64:MDEyMzQ1Njc4OUFCQ0RFRjAxMjM0NTY3ODlBQkNERUY=}
security.jwt.issuer=${JWT_ISSUER:coactivity-core}
security.jwt.audience=${JWT_AUDIENCE:coactivity-api}
