spring.application.name=CoActivity Platform
spring.jpa.hibernate.ddl-auto=create
# spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.url={your_url}
spring.datasource.username={your_password}
spring.datasource.password={your_username}

# Yandex SMTP Configuration
spring.mail.host=smtp.yandex.com
spring.mail.port=465
spring.mail.username=bumagin.nicita@yandex.ru
spring.mail.password=abrxxjsxwumdvvea
spring.mail.protocol=smtps

# Additional properties for secure connection
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.socketFactory.port=465
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory