ALTER TABLE rooms ADD COLUMN status VARCHAR(20);

UPDATE rooms
SET status = CASE
  WHEN is_active THEN 'ACTIVE'
  ELSE 'INACTIVE'
END
WHERE status IS NULL;

ALTER TABLE rooms
  ALTER COLUMN status SET NOT NULL;

ALTER TABLE rooms
  ADD CONSTRAINT chk_rooms_status
  CHECK (status IN ('ACTIVE', 'INACTIVE', 'COMPLETED'));

ALTER TABLE rooms DROP COLUMN is_active;
