package com.coactivity.controller.dto.request;

import com.coactivity.controller.ApiController;
import com.coactivity.controller.dto.response.VerificationResponse;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.Data;

/**
 * Request DTO for verifying a scanned QR code during physical meeting check-in.
 * <p>
 * Contains the scanned QR code data and room context to validate participant eligibility for
 * in-person event access. The verification process checks:
 * </p>
 * <ul>
 *   <li>QR code exists and is not expired (1-minute validity)</li>
 *   <li>QR code hasn't been previously used (one-time use)</li>
 *   <li>Scanning user is a participant of the specified room</li>
 *   <li>QR code belongs to the correct room context</li>
 * </ul>
 *
 * @see VerificationResponse
 * @see ApiController#verifyQrCode(String, VerifyQrCodeRequest)
 */
@Data
public class VerifyQrCodeRequest {

  /**
   * The unique QR code string scanned from the physical display.
   * <p>
   * This is the cryptographic string generated by {@link ApiController#generateQrCode} that was
   * encoded in the QR image. Typically 32-character URL-safe base64 string.
   * </p>
   */
  @NotBlank(message = "QR code cannot be blank or null")
  private String qrCode;

  /**
   * The room identifier where the QR code scanning is occurring.
   * <p>
   * Provides context for the verification to ensure the QR code is being used in the correct
   * physical location and matches the intended room.
   * </p>
   */
  @NotNull(message = "Room ID is required for verification context")
  private Long roomId;
}