management:
  endpoint:
    health:
      show-details: ${MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS:never}

spring:
  mail:
    host: ${SPRING_MAIL_HOST:smtp.yandex.ru}
    port: ${SPRING_MAIL_PORT:587}
    properties:
      mail:
        smtp:
          auth: ${SPRING_MAIL_SMTP_AUTH:true}
          starttls:
            enable: ${SPRING_MAIL_SMTP_STARTTLS_ENABLE:true}
            required: ${SPRING_MAIL_SMTP_STARTTLS_REQUIRED:true}

