package com.coactivity.service;

import com.coactivity.service.dto.TokenPayload;
import java.nio.charset.StandardCharsets;
import java.util.Base64;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import javax.crypto.Cipher;
import javax.crypto.spec.SecretKeySpec;

/**
 * Handles creation and validation of the simple opaque tokens used by the controllers.
 * <p>
 * Tokens are lightweight wrappers around a user's login (email) and password. They are encrypted
 * with a server-side secret and encoded before being returned to the client. 
 * </p>
 */
public class TokenService {

  /**
   * Hard-coded secret used to encrypt/decrypt the token payload.
   * <p>
   * Must be 16 bytes to work with AES-128. In production this should live in a secure config store.
   * </p>
   */
  private static final String SECRET_KEY = "CoActivitySecret!";

  private static final String ENCRYPTION_ALGORITHM = "AES/ECB/PKCS5Padding";

  private final Map<String, String> activeTokens = new ConcurrentHashMap<>();

  /**
   * Creates an encoded token containing the provided login (email) and password.
   *
   * @param login    user email provided during authentication
   * @param password raw password; will be encrypted inside the token
   * @return opaque token string that clients must include in subsequent authenticated requests
   * @throws IllegalStateException if the encryption operation fails
   */
  public String createToken(String login, String password) {
    String payload = login + ":" + password;
    byte[] encryptedPayload = encrypt(payload);
    return Base64.getEncoder().encodeToString(encryptedPayload);
  }

  /**
   * Registers a freshly issued token as the only active token for the provided login. If a previous
   * token existed it is automatically invalidated.
   *
   * @param login user login (email) tied to the token
   * @param token encoded token generated by {@link #createToken(String, String)}
   */
  public void registerActiveToken(String login, String token) {
    activeTokens.put(login, token);
  }

  /**
   * Indicates whether the provided token is currently active for the login embedded within it.
   *
   * @param token encoded token supplied by the client
   * @return {@code true} if this token matches the active entry for the contained login
   */
  public boolean isTokenActive(String token) {
    TokenPayload payload = decodeToken(token);
    return token.equals(activeTokens.get(payload.login()));
  }

  /**
   * Removes the active token associated with the login contained in the provided token string.
   *
   * @param token encoded token supplied by the client
   */
  public void invalidateToken(String token) {
    TokenPayload payload = decodeToken(token);
    activeTokens.remove(payload.login(), token);
  }

  /**
   * Explicitly removes the active token for the given login, if any.
   *
   * @param login user login (email)
   */
  public void clearActiveToken(String login) {
    activeTokens.remove(login);
  }

  /**
   * Decrypts the provided token and extracts the login (email) and password.
   *
   * @param token encoded token previously created by {@link #createToken(String, String)}
   * @return {@link TokenPayload} containing the original login and password
   * @throws IllegalArgumentException if the token cannot be decoded or decrypted
   */
  public TokenPayload decodeToken(String token) {
    try {
      byte[] encryptedPayload = Base64.getDecoder().decode(token);
      String payload = decrypt(encryptedPayload);
      String[] parts = payload.split(":", 2);
      if (parts.length != 2) {
        throw new IllegalArgumentException("Token payload is malformed");
      }
      return new TokenPayload(parts[0], parts[1]);
    } catch (IllegalArgumentException ex) {
      throw ex;
    } catch (Exception ex) {
      throw new IllegalArgumentException("Failed to decode token", ex);
    }
  }

  private byte[] encrypt(String payload) {
    try {
      Cipher cipher = Cipher.getInstance(ENCRYPTION_ALGORITHM);
      SecretKeySpec secretKeySpec =
          new SecretKeySpec(SECRET_KEY.getBytes(StandardCharsets.UTF_8), "AES");
      cipher.init(Cipher.ENCRYPT_MODE, secretKeySpec);
      return cipher.doFinal(payload.getBytes(StandardCharsets.UTF_8));
    } catch (Exception ex) {
      throw new IllegalStateException("Failed to encrypt authentication token", ex);
    }
  }

  private String decrypt(byte[] encryptedPayload) {
    try {
      Cipher cipher = Cipher.getInstance(ENCRYPTION_ALGORITHM);
      SecretKeySpec secretKeySpec =
          new SecretKeySpec(SECRET_KEY.getBytes(StandardCharsets.UTF_8), "AES");
      cipher.init(Cipher.DECRYPT_MODE, secretKeySpec);
      byte[] decrypted = cipher.doFinal(encryptedPayload);
      return new String(decrypted, StandardCharsets.UTF_8);
    } catch (Exception ex) {
      throw new IllegalStateException("Failed to decrypt authentication token", ex);
    }
  }

}
