package com.coactivity.service;

import com.coactivity.DataRepository;
import com.coactivity.controller.dto.request.UserRegistrationRequest;
import com.coactivity.domain.User;
import com.coactivity.repository.UserRepository;
import com.coactivity.repository.impl.UserRepositoryImpl;
import java.util.ArrayList;
import org.springframework.stereotype.Service;

/**
 * Handles user profile operations including registration, profile management, and account
 * lifecycle.
 */
@Service
public class UserProfileService {

  private final UserRepository userRepository;
  private final TokenService tokenService;
  private final DataRepository repository;

  public UserProfileService() {
    this.repository = new DataRepository();
    this.userRepository = new UserRepositoryImpl(repository);
    this.tokenService = new TokenService();
  }


  /**
   * Registers a new user in the system.
   *
   * @param request the user registration data
   * @return the newly created User entity
   * @throws IllegalArgumentException if user with same login already exists or required fields are
   *                                  missing
   */
  public User registerUser(UserRegistrationRequest request) {
    if (request.getLogin() == null || request.getLogin().trim().isEmpty()) {
      throw new IllegalArgumentException("Login is required");
    }
    if (request.getPassword() == null || request.getPassword().trim().isEmpty()) {
      throw new IllegalArgumentException("Password is required");
    }
    if (request.getUsername() == null || request.getUsername().trim().isEmpty()) {
      throw new IllegalArgumentException("Username is required");
    }

//    User existingUser = userRepository.findByLogin(request.getLogin());
//    if (existingUser != null) {
//      throw new IllegalArgumentException("User with this login already exists");
//    }

    // Create new user
    User newUser = new User(
        null, // ID will be generated by repository
        request.getLogin(),
        request.getUsername(),
        request.getPassword(), // In production, this should be hashed!
        request.getDateOfBirth(),
        request.getCity(),
        request.getCountry(),
        request.getDescription(),
        request.getAvatarId(),
        new ArrayList<>(), // Empty rooms list
        new ArrayList<>()  // Empty notifications list
    );

    // Save to repository
//    return userRepository.save(newUser);
    return newUser;
  }
}
